spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: cbc81a57-6360-4906-a388-80d67b47aa97
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8081
      #取消控制台懒加载
      eager: true
  #  统一异常处理捕捉
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dijiang?serverTimezone=GMT%2B8&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
#      password: admin123
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  servlet:
    multipart:
      max-file-size: 2MB  # 设置单个文件大小，单位MB和KB都可以
      max-request-size: 500MB # 设置总上传的数据大小，单位MB和KB都可以
      # enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:  #配置redis连接池
      pool:
        max-active: 200
        max-idle: 8
        min-idle: 4


  main:
    allow-bean-definition-overriding: true
  resources:
#    不为本地资源文件建立映射
    add-mappings: false
  application:
    name: staffMannagement-provider
  security:
    user:
      name: admin
      password: admin


# 修改端口
server:
  port: 9001
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
dijiang:
  fastDFS:
    url: http://192.168.73.128/
  web:
    service: http://localhost:8080/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.73.128:22122

jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: challenger-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico
  # 有效时间
  validTime: 7


app:
  id: SampleApp
apollo:
  meta: http://192.168.1.107:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

Token:
  headerToken: djtoken

